### ISSUE TITLE
API overhaul

### ISSUE THREAD

**Issue by bestouff** [zesterer/ariadne#12]
Here's my christmas wishlist for the API overhaul:
- [x] allow working with non-`str` data (#8)
- [ ] get rid of initial location in `Report::build()` (#3)
- [ ] pass `Cache` by shared reference to allow several threads to access it (#10)
- [ ] allow `SourceId` (which may be e.g. a reference or an index) to only be interpreted by `Cache` (don't require it to be `Display`)
and maybe this one would be nice:
- [ ] allow somehow to print differently to use the errors in a TUI(#11)

Feel free to edit or comment.
